aqmd:
  netty:
    bossThreadSize: 1
    deal-handler-thread-size: 10
    defaultTimeout: 30
    direct-access-command: 20001,20002,20021,20022
    direct-access-flag: 1
    max-frame-length: 2147483647
    max-timeout: 60
    packetHeaderLength: 4
    port: 28901
    serviceLoggerLevel: debug
    worker-thread-size: 3
    writer-idle: 200
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/
redis:
  hostName: 127.0.0.1
  password: wxpker
  port: 6379
second:
  referrer:
    award: true
server:
  context-path: /market
  port: 6004
spring:
  application:
    name: bitrade-market
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://wxpker:wxpker@localhost:27017/exchange
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 200
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: 666666pk
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    validationQuery: SELECT 1
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: 112.74.59.207:9092
    consumer:
      auto:
        commit:
          interval: 100
        offset:
          reset: earliest
      concurrency: 9
      enable:
        auto:
          commit: false
      group:
        id: default-group
      maxPollRecordsConfig: 50
      session:
        timeout: 15000
    producer:
      batch:
        size: 256
      buffer:
        memory: 1048576
      linger: 1
      retries: 0
  session:
    store-type: none



jetcache:
  areaInCacheName: false
  local:
    default:
      keyConvertor: fastjson
      type: linkedhashmap
  statIntervalMinutes: 60
influx:
  database: bitcola
  host: http://120.79.250.164:8086
